name: 'Run Terragrunt Github Action'
description: 'Runs Terragrunt commands via GitHub Actions.'
author:  'denis256 <denis.o@linux.com>'
branding:
  icon: 'cloud'
  color: 'red'
inputs:
  tg_version:
    description: 'Terraform version to install.'
    required: true
    default: 'latest'
  tf_version:
    description: 'Terraform version to install.'
    required: true
    default: 'latest'
  tg_command:
    description: 'Terragrunt subcommand to execute.'
    required: true
  tg_dir:
    description: 'Directory to run Terragrunt in.'
    required: true
runs:
  using: 'docker'
  image: './Dockerfile'