name: "Docker image building"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set outputs
        id: vars
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      - name: Using version
        run: echo ${{ steps.vars.outputs.branch }}
      - name: Build image
        run: "cd src && docker build -t denis256/tg-gh-action:${{ steps.vars.outputs.branch }} . "
      - name: Login registry
        run: "docker login -u ${{ secrets.CI_USER }} -p ${{ secrets.CI_PWD }}"
      - name: Push image
        run: "docker push denis256/tg-gh-action:${{ steps.vars.outputs.branch }}"