name: "Docker images building"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Build image
        run: "cd docker && docker build -t denis256/tg-gh-action:${{ github.head_ref }}.${{ github.sha }} . "
      - name: Login registry
        run: "docker login -u ${{ secrets.CI_USER }} -p ${{ secrets.CI_PWD }}"
      - name: Push image
        run: "docker push denis256/tg-gh-action:${{ github.head_ref }}.${{ github.sha }}"