name: "Docker image building"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-list --tags --max-count=1)" >> $GITHUB_OUTPUT
      - name: Using version
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: Build image
        run: "cd src && docker build -t denis256/tg-gh-action:${{ steps.vars.outputs.sha_short }} . "
      - name: Login registry
        run: "docker login -u ${{ secrets.CI_USER }} -p ${{ secrets.CI_PWD }}"
      - name: Push image
        run: "docker push denis256/tg-gh-action:${{ steps.vars.outputs.sha_short }}"